# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: HerCep Services Corp.
description: Financial Services
url: https://github.com/herrerajeff/hercep.git

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Jeffrey Herrera
  email: herrera.jeffrey@gmail.com
  uri: jeffreyherrera.com
  bio: Designer

# Permalink structure and pagination options
permalink: none
paginate: 10
paginate_path: 'page:num'
excerpt_separator: ''

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: rouge

# Extending Jekyll
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
